package model;
// Generated 23-may-2015 18:32:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bodega generated by hbm2java
 */
@Entity
@Table(name="BODEGA"
    ,schema="GRUPO8"
)
public class Bodega  implements java.io.Serializable {


     private int idBodega;
     private BigDecimal cantidadPasillos;
     private BigDecimal estantesPorPasillo;
     private String nombre2;
     private BigDecimal cantidadEstante;
     private BigDecimal productoPorEstante;
     private String ubicacion;
     private Set<Inventario> inventarios = new HashSet<Inventario>(0);

    public Bodega() {
    }

	
    public Bodega(int idBodega, String nombre2, String ubicacion) {
        this.idBodega = idBodega;
        this.nombre2 = nombre2;
        this.ubicacion = ubicacion;
    }
    public Bodega(int idBodega, BigDecimal cantidadPasillos, BigDecimal estantesPorPasillo, String nombre2, BigDecimal cantidadEstante, BigDecimal productoPorEstante, String ubicacion, Set<Inventario> inventarios) {
       this.idBodega = idBodega;
       this.cantidadPasillos = cantidadPasillos;
       this.estantesPorPasillo = estantesPorPasillo;
       this.nombre2 = nombre2;
       this.cantidadEstante = cantidadEstante;
       this.productoPorEstante = productoPorEstante;
       this.ubicacion = ubicacion;
       this.inventarios = inventarios;
    }
   
     @Id 

    
    @Column(name="ID_BODEGA", unique=true, nullable=false, precision=6, scale=0)
    public int getIdBodega() {
        return this.idBodega;
    }
    
    public void setIdBodega(int idBodega) {
        this.idBodega = idBodega;
    }

    
    @Column(name="CANTIDAD_PASILLOS", precision=22, scale=0)
    public BigDecimal getCantidadPasillos() {
        return this.cantidadPasillos;
    }
    
    public void setCantidadPasillos(BigDecimal cantidadPasillos) {
        this.cantidadPasillos = cantidadPasillos;
    }

    
    @Column(name="ESTANTES_POR_PASILLO", precision=22, scale=0)
    public BigDecimal getEstantesPorPasillo() {
        return this.estantesPorPasillo;
    }
    
    public void setEstantesPorPasillo(BigDecimal estantesPorPasillo) {
        this.estantesPorPasillo = estantesPorPasillo;
    }

    
    @Column(name="NOMBRE2", nullable=false, length=30)
    public String getNombre2() {
        return this.nombre2;
    }
    
    public void setNombre2(String nombre2) {
        this.nombre2 = nombre2;
    }

    
    @Column(name="CANTIDAD_ESTANTE", precision=22, scale=0)
    public BigDecimal getCantidadEstante() {
        return this.cantidadEstante;
    }
    
    public void setCantidadEstante(BigDecimal cantidadEstante) {
        this.cantidadEstante = cantidadEstante;
    }

    
    @Column(name="PRODUCTO_POR_ESTANTE", precision=22, scale=0)
    public BigDecimal getProductoPorEstante() {
        return this.productoPorEstante;
    }
    
    public void setProductoPorEstante(BigDecimal productoPorEstante) {
        this.productoPorEstante = productoPorEstante;
    }

    
    @Column(name="UBICACION", nullable=false, length=150)
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bodega")
    public Set<Inventario> getInventarios() {
        return this.inventarios;
    }
    
    public void setInventarios(Set<Inventario> inventarios) {
        this.inventarios = inventarios;
    }




}


