package model;
// Generated 23-may-2015 18:32:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Catalogo generated by hbm2java
 */
@Entity
@Table(name="CATALOGO"
    ,schema="GRUPO8"
)
public class Catalogo  implements java.io.Serializable {


     private int idCatalogo;
     private TipoCatalogo tipoCatalogo;
     private String nombre;
     private String descripcion;
     private Set<Proveedor> proveedors = new HashSet<Proveedor>(0);
     private Set<Transaccion> transaccions = new HashSet<Transaccion>(0);
     private Set<Devolucion> devolucions = new HashSet<Devolucion>(0);
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<Producto> productos = new HashSet<Producto>(0);

    public Catalogo() {
    }

	
    public Catalogo(int idCatalogo, TipoCatalogo tipoCatalogo, String nombre) {
        this.idCatalogo = idCatalogo;
        this.tipoCatalogo = tipoCatalogo;
        this.nombre = nombre;
    }
    public Catalogo(int idCatalogo, TipoCatalogo tipoCatalogo, String nombre, String descripcion, Set<Proveedor> proveedors, Set<Transaccion> transaccions, Set<Devolucion> devolucions, Set<Usuario> usuarios, Set<Producto> productos) {
       this.idCatalogo = idCatalogo;
       this.tipoCatalogo = tipoCatalogo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.proveedors = proveedors;
       this.transaccions = transaccions;
       this.devolucions = devolucions;
       this.usuarios = usuarios;
       this.productos = productos;
    }
   
     @Id 

    
    @Column(name="ID_CATALOGO", unique=true, nullable=false, precision=6, scale=0)
    public int getIdCatalogo() {
        return this.idCatalogo;
    }
    
    public void setIdCatalogo(int idCatalogo) {
        this.idCatalogo = idCatalogo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_TIPO_CATALOGO", nullable=false)
    public TipoCatalogo getTipoCatalogo() {
        return this.tipoCatalogo;
    }
    
    public void setTipoCatalogo(TipoCatalogo tipoCatalogo) {
        this.tipoCatalogo = tipoCatalogo;
    }

    
    @Column(name="NOMBRE", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="DESCRIPCION", length=150)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catalogo")
    public Set<Proveedor> getProveedors() {
        return this.proveedors;
    }
    
    public void setProveedors(Set<Proveedor> proveedors) {
        this.proveedors = proveedors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catalogo")
    public Set<Transaccion> getTransaccions() {
        return this.transaccions;
    }
    
    public void setTransaccions(Set<Transaccion> transaccions) {
        this.transaccions = transaccions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catalogo")
    public Set<Devolucion> getDevolucions() {
        return this.devolucions;
    }
    
    public void setDevolucions(Set<Devolucion> devolucions) {
        this.devolucions = devolucions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catalogo")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catalogo")
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


