package model;
// Generated 17-may-2015 20:35:06 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int idCliente;
     private BigDecimal idPersona;
     private Set<Devolucion> devolucions = new HashSet<Devolucion>(0);
     private Set<Requisicion> requisicions = new HashSet<Requisicion>(0);

    public Cliente() {
    }

	
    public Cliente(int idCliente, BigDecimal idPersona) {
        this.idCliente = idCliente;
        this.idPersona = idPersona;
    }
    public Cliente(int idCliente, BigDecimal idPersona, Set<Devolucion> devolucions, Set<Requisicion> requisicions) {
       this.idCliente = idCliente;
       this.idPersona = idPersona;
       this.devolucions = devolucions;
       this.requisicions = requisicions;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public BigDecimal getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(BigDecimal idPersona) {
        this.idPersona = idPersona;
    }
    public Set<Devolucion> getDevolucions() {
        return this.devolucions;
    }
    
    public void setDevolucions(Set<Devolucion> devolucions) {
        this.devolucions = devolucions;
    }
    public Set<Requisicion> getRequisicions() {
        return this.requisicions;
    }
    
    public void setRequisicions(Set<Requisicion> requisicions) {
        this.requisicions = requisicions;
    }




}


