package model;
// Generated 23-may-2015 18:32:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="CLIENTE"
    ,schema="GRUPO8"
)
public class Cliente  implements java.io.Serializable {


     private int idCliente;
     private BigDecimal idPersona;
     private Set<Devolucion> devolucions = new HashSet<Devolucion>(0);
     private Set<Requisicion> requisicions = new HashSet<Requisicion>(0);

    public Cliente() {
    }

	
    public Cliente(int idCliente, BigDecimal idPersona) {
        this.idCliente = idCliente;
        this.idPersona = idPersona;
    }
    public Cliente(int idCliente, BigDecimal idPersona, Set<Devolucion> devolucions, Set<Requisicion> requisicions) {
       this.idCliente = idCliente;
       this.idPersona = idPersona;
       this.devolucions = devolucions;
       this.requisicions = requisicions;
    }
   
     @Id 

    
    @Column(name="ID_CLIENTE", unique=true, nullable=false, precision=6, scale=0)
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }

    
    @Column(name="ID_PERSONA", nullable=false, precision=22, scale=0)
    public BigDecimal getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(BigDecimal idPersona) {
        this.idPersona = idPersona;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set<Devolucion> getDevolucions() {
        return this.devolucions;
    }
    
    public void setDevolucions(Set<Devolucion> devolucions) {
        this.devolucions = devolucions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set<Requisicion> getRequisicions() {
        return this.requisicions;
    }
    
    public void setRequisicions(Set<Requisicion> requisicions) {
        this.requisicions = requisicions;
    }




}


