package model;
// Generated 17-may-2015 20:35:06 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cotizacion generated by hbm2java
 */
public class Cotizacion  implements java.io.Serializable {


     private int idCotizacion;
     private Pedido pedido;
     private Proveedor proveedor;
     private BigDecimal estadoCot;
     private Set<OrdenDeCompra> ordenDeCompras = new HashSet<OrdenDeCompra>(0);

    public Cotizacion() {
    }

	
    public Cotizacion(int idCotizacion, Pedido pedido, Proveedor proveedor, BigDecimal estadoCot) {
        this.idCotizacion = idCotizacion;
        this.pedido = pedido;
        this.proveedor = proveedor;
        this.estadoCot = estadoCot;
    }
    public Cotizacion(int idCotizacion, Pedido pedido, Proveedor proveedor, BigDecimal estadoCot, Set<OrdenDeCompra> ordenDeCompras) {
       this.idCotizacion = idCotizacion;
       this.pedido = pedido;
       this.proveedor = proveedor;
       this.estadoCot = estadoCot;
       this.ordenDeCompras = ordenDeCompras;
    }
   
    public int getIdCotizacion() {
        return this.idCotizacion;
    }
    
    public void setIdCotizacion(int idCotizacion) {
        this.idCotizacion = idCotizacion;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public BigDecimal getEstadoCot() {
        return this.estadoCot;
    }
    
    public void setEstadoCot(BigDecimal estadoCot) {
        this.estadoCot = estadoCot;
    }
    public Set<OrdenDeCompra> getOrdenDeCompras() {
        return this.ordenDeCompras;
    }
    
    public void setOrdenDeCompras(Set<OrdenDeCompra> ordenDeCompras) {
        this.ordenDeCompras = ordenDeCompras;
    }




}


