package model;
// Generated 17-may-2015 20:35:06 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DetalleDeOrdenCompra generated by hbm2java
 */
public class DetalleDeOrdenCompra  implements java.io.Serializable {


     private int idDetalleDeOrdenCompra;
     private OrdenDeCompra ordenDeCompra;
     private Producto producto;
     private BigDecimal cantidad;

    public DetalleDeOrdenCompra() {
    }

    public DetalleDeOrdenCompra(int idDetalleDeOrdenCompra, OrdenDeCompra ordenDeCompra, Producto producto, BigDecimal cantidad) {
       this.idDetalleDeOrdenCompra = idDetalleDeOrdenCompra;
       this.ordenDeCompra = ordenDeCompra;
       this.producto = producto;
       this.cantidad = cantidad;
    }
   
    public int getIdDetalleDeOrdenCompra() {
        return this.idDetalleDeOrdenCompra;
    }
    
    public void setIdDetalleDeOrdenCompra(int idDetalleDeOrdenCompra) {
        this.idDetalleDeOrdenCompra = idDetalleDeOrdenCompra;
    }
    public OrdenDeCompra getOrdenDeCompra() {
        return this.ordenDeCompra;
    }
    
    public void setOrdenDeCompra(OrdenDeCompra ordenDeCompra) {
        this.ordenDeCompra = ordenDeCompra;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }




}


