package model;
// Generated 17-may-2015 20:35:06 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DetalleRequisicion generated by hbm2java
 */
public class DetalleRequisicion  implements java.io.Serializable {


     private int idDetalleRequisicion;
     private Producto producto;
     private Requisicion requisicion;
     private BigDecimal catidad;

    public DetalleRequisicion() {
    }

    public DetalleRequisicion(int idDetalleRequisicion, Producto producto, Requisicion requisicion, BigDecimal catidad) {
       this.idDetalleRequisicion = idDetalleRequisicion;
       this.producto = producto;
       this.requisicion = requisicion;
       this.catidad = catidad;
    }
   
    public int getIdDetalleRequisicion() {
        return this.idDetalleRequisicion;
    }
    
    public void setIdDetalleRequisicion(int idDetalleRequisicion) {
        this.idDetalleRequisicion = idDetalleRequisicion;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Requisicion getRequisicion() {
        return this.requisicion;
    }
    
    public void setRequisicion(Requisicion requisicion) {
        this.requisicion = requisicion;
    }
    public BigDecimal getCatidad() {
        return this.catidad;
    }
    
    public void setCatidad(BigDecimal catidad) {
        this.catidad = catidad;
    }




}


