package model;
// Generated 17-may-2015 20:35:06 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DetallePedido generated by hbm2java
 */
public class DetallePedido  implements java.io.Serializable {


     private int idDetalleProducto;
     private Pedido pedido;
     private Producto producto;
     private BigDecimal cantidad;

    public DetallePedido() {
    }

    public DetallePedido(int idDetalleProducto, Pedido pedido, Producto producto, BigDecimal cantidad) {
       this.idDetalleProducto = idDetalleProducto;
       this.pedido = pedido;
       this.producto = producto;
       this.cantidad = cantidad;
    }
   
    public int getIdDetalleProducto() {
        return this.idDetalleProducto;
    }
    
    public void setIdDetalleProducto(int idDetalleProducto) {
        this.idDetalleProducto = idDetalleProducto;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }




}


