package model;
// Generated 23-may-2015 18:32:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetalleDevolucion generated by hbm2java
 */
@Entity
@Table(name="DETALLE_DEVOLUCION"
    ,schema="GRUPO8"
)
public class DetalleDevolucion  implements java.io.Serializable {


     private int idDetalleDevolucion;
     private Producto producto;
     private Devolucion devolucion;
     private BigDecimal cantidad;

    public DetalleDevolucion() {
    }

    public DetalleDevolucion(int idDetalleDevolucion, Producto producto, Devolucion devolucion, BigDecimal cantidad) {
       this.idDetalleDevolucion = idDetalleDevolucion;
       this.producto = producto;
       this.devolucion = devolucion;
       this.cantidad = cantidad;
    }
   
     @Id 

    
    @Column(name="ID_DETALLE_DEVOLUCION", unique=true, nullable=false, precision=6, scale=0)
    public int getIdDetalleDevolucion() {
        return this.idDetalleDevolucion;
    }
    
    public void setIdDetalleDevolucion(int idDetalleDevolucion) {
        this.idDetalleDevolucion = idDetalleDevolucion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PRODUCTO", nullable=false)
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_DEVOLUCION", nullable=false)
    public Devolucion getDevolucion() {
        return this.devolucion;
    }
    
    public void setDevolucion(Devolucion devolucion) {
        this.devolucion = devolucion;
    }

    
    @Column(name="CANTIDAD", nullable=false, precision=22, scale=0)
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }




}


