package model;
// Generated 23-may-2015 18:32:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DetalleProducto generated by hbm2java
 */
@Entity
@Table(name="DETALLE_PRODUCTO"
    ,schema="GRUPO8"
)
public class DetalleProducto  implements java.io.Serializable {


     private int idDetalleProducto;
     private BigDecimal idProducto;
     private BigDecimal cantidad;
     private String nombre;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public DetalleProducto() {
    }

	
    public DetalleProducto(int idDetalleProducto, BigDecimal idProducto, BigDecimal cantidad, String nombre) {
        this.idDetalleProducto = idDetalleProducto;
        this.idProducto = idProducto;
        this.cantidad = cantidad;
        this.nombre = nombre;
    }
    public DetalleProducto(int idDetalleProducto, BigDecimal idProducto, BigDecimal cantidad, String nombre, Set<Producto> productos) {
       this.idDetalleProducto = idDetalleProducto;
       this.idProducto = idProducto;
       this.cantidad = cantidad;
       this.nombre = nombre;
       this.productos = productos;
    }
   
     @Id 

    
    @Column(name="ID_DETALLE_PRODUCTO", unique=true, nullable=false, precision=6, scale=0)
    public int getIdDetalleProducto() {
        return this.idDetalleProducto;
    }
    
    public void setIdDetalleProducto(int idDetalleProducto) {
        this.idDetalleProducto = idDetalleProducto;
    }

    
    @Column(name="ID_PRODUCTO", nullable=false, precision=22, scale=0)
    public BigDecimal getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(BigDecimal idProducto) {
        this.idProducto = idProducto;
    }

    
    @Column(name="CANTIDAD", nullable=false, precision=22, scale=0)
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="NOMBRE", nullable=false, length=150)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="detalleProducto")
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


