package model;
// Generated 17-may-2015 20:35:06 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * DetalleProducto generated by hbm2java
 */
public class DetalleProducto  implements java.io.Serializable {


     private int idDetalleProducto;
     private BigDecimal idProducto;
     private BigDecimal cantidad;
     private String nombre;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public DetalleProducto() {
    }

	
    public DetalleProducto(int idDetalleProducto, BigDecimal idProducto, BigDecimal cantidad, String nombre) {
        this.idDetalleProducto = idDetalleProducto;
        this.idProducto = idProducto;
        this.cantidad = cantidad;
        this.nombre = nombre;
    }
    public DetalleProducto(int idDetalleProducto, BigDecimal idProducto, BigDecimal cantidad, String nombre, Set<Producto> productos) {
       this.idDetalleProducto = idDetalleProducto;
       this.idProducto = idProducto;
       this.cantidad = cantidad;
       this.nombre = nombre;
       this.productos = productos;
    }
   
    public int getIdDetalleProducto() {
        return this.idDetalleProducto;
    }
    
    public void setIdDetalleProducto(int idDetalleProducto) {
        this.idDetalleProducto = idDetalleProducto;
    }
    public BigDecimal getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(BigDecimal idProducto) {
        this.idProducto = idProducto;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


