package model;
// Generated 23-may-2015 18:32:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetalleRequisicion generated by hbm2java
 */
@Entity
@Table(name="DETALLE_REQUISICION"
    ,schema="GRUPO8"
)
public class DetalleRequisicion  implements java.io.Serializable {


     private int idDetalleRequisicion;
     private Requisicion requisicion;
     private Producto producto;
     private BigDecimal catidad;

    public DetalleRequisicion() {
    }

    public DetalleRequisicion(int idDetalleRequisicion, Requisicion requisicion, Producto producto, BigDecimal catidad) {
       this.idDetalleRequisicion = idDetalleRequisicion;
       this.requisicion = requisicion;
       this.producto = producto;
       this.catidad = catidad;
    }
   
     @Id 

    
    @Column(name="ID_DETALLE_REQUISICION", unique=true, nullable=false, precision=6, scale=0)
    public int getIdDetalleRequisicion() {
        return this.idDetalleRequisicion;
    }
    
    public void setIdDetalleRequisicion(int idDetalleRequisicion) {
        this.idDetalleRequisicion = idDetalleRequisicion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_REQUISICION", nullable=false)
    public Requisicion getRequisicion() {
        return this.requisicion;
    }
    
    public void setRequisicion(Requisicion requisicion) {
        this.requisicion = requisicion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PRODUCTO", nullable=false)
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    
    @Column(name="CATIDAD", nullable=false, precision=22, scale=0)
    public BigDecimal getCatidad() {
        return this.catidad;
    }
    
    public void setCatidad(BigDecimal catidad) {
        this.catidad = catidad;
    }




}


