package model;
// Generated 23-may-2015 18:32:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetalleDeOrdenCompra generated by hbm2java
 */
@Entity
@Table(name="DETALLE_DE_ORDEN_COMPRA"
    ,schema="GRUPO8"
)
public class DetalleDeOrdenCompra  implements java.io.Serializable {


     private int idDetalleDeOrdenCompra;
     private Producto producto;
     private OrdenDeCompra ordenDeCompra;
     private BigDecimal cantidad;

    public DetalleDeOrdenCompra() {
    }

    public DetalleDeOrdenCompra(int idDetalleDeOrdenCompra, Producto producto, OrdenDeCompra ordenDeCompra, BigDecimal cantidad) {
       this.idDetalleDeOrdenCompra = idDetalleDeOrdenCompra;
       this.producto = producto;
       this.ordenDeCompra = ordenDeCompra;
       this.cantidad = cantidad;
    }
   
     @Id 

    
    @Column(name="ID_DETALLE_DE_ORDEN_COMPRA", unique=true, nullable=false, precision=6, scale=0)
    public int getIdDetalleDeOrdenCompra() {
        return this.idDetalleDeOrdenCompra;
    }
    
    public void setIdDetalleDeOrdenCompra(int idDetalleDeOrdenCompra) {
        this.idDetalleDeOrdenCompra = idDetalleDeOrdenCompra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PRODUCTO", nullable=false)
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ORDEN", nullable=false)
    public OrdenDeCompra getOrdenDeCompra() {
        return this.ordenDeCompra;
    }
    
    public void setOrdenDeCompra(OrdenDeCompra ordenDeCompra) {
        this.ordenDeCompra = ordenDeCompra;
    }

    
    @Column(name="CANTIDAD", nullable=false, precision=22, scale=0)
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }




}


