package model;
// Generated 17-may-2015 20:35:06 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DetalleDevolucion generated by hbm2java
 */
public class DetalleDevolucion  implements java.io.Serializable {


     private int idDetalleDevolucion;
     private Devolucion devolucion;
     private Producto producto;
     private BigDecimal cantidad;

    public DetalleDevolucion() {
    }

    public DetalleDevolucion(int idDetalleDevolucion, Devolucion devolucion, Producto producto, BigDecimal cantidad) {
       this.idDetalleDevolucion = idDetalleDevolucion;
       this.devolucion = devolucion;
       this.producto = producto;
       this.cantidad = cantidad;
    }
   
    public int getIdDetalleDevolucion() {
        return this.idDetalleDevolucion;
    }
    
    public void setIdDetalleDevolucion(int idDetalleDevolucion) {
        this.idDetalleDevolucion = idDetalleDevolucion;
    }
    public Devolucion getDevolucion() {
        return this.devolucion;
    }
    
    public void setDevolucion(Devolucion devolucion) {
        this.devolucion = devolucion;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }




}


