package model;
// Generated 23-may-2015 18:32:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Devolucion generated by hbm2java
 */
@Entity
@Table(name="DEVOLUCION"
    ,schema="GRUPO8"
)
public class Devolucion  implements java.io.Serializable {


     private int idDevolucion;
     private Requisicion requisicion;
     private Proveedor proveedor;
     private OrdenDeCompra ordenDeCompra;
     private Cliente cliente;
     private Catalogo catalogo;
     private Set<DetalleDevolucion> detalleDevolucions = new HashSet<DetalleDevolucion>(0);
     private Set<Transaccion> transaccions = new HashSet<Transaccion>(0);

    public Devolucion() {
    }

	
    public Devolucion(int idDevolucion, Proveedor proveedor, Cliente cliente, Catalogo catalogo) {
        this.idDevolucion = idDevolucion;
        this.proveedor = proveedor;
        this.cliente = cliente;
        this.catalogo = catalogo;
    }
    public Devolucion(int idDevolucion, Requisicion requisicion, Proveedor proveedor, OrdenDeCompra ordenDeCompra, Cliente cliente, Catalogo catalogo, Set<DetalleDevolucion> detalleDevolucions, Set<Transaccion> transaccions) {
       this.idDevolucion = idDevolucion;
       this.requisicion = requisicion;
       this.proveedor = proveedor;
       this.ordenDeCompra = ordenDeCompra;
       this.cliente = cliente;
       this.catalogo = catalogo;
       this.detalleDevolucions = detalleDevolucions;
       this.transaccions = transaccions;
    }
   
     @Id 

    
    @Column(name="ID_DEVOLUCION", unique=true, nullable=false, precision=6, scale=0)
    public int getIdDevolucion() {
        return this.idDevolucion;
    }
    
    public void setIdDevolucion(int idDevolucion) {
        this.idDevolucion = idDevolucion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_REQUISICION")
    public Requisicion getRequisicion() {
        return this.requisicion;
    }
    
    public void setRequisicion(Requisicion requisicion) {
        this.requisicion = requisicion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PROVEEDOR", nullable=false)
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ORDEN")
    public OrdenDeCompra getOrdenDeCompra() {
        return this.ordenDeCompra;
    }
    
    public void setOrdenDeCompra(OrdenDeCompra ordenDeCompra) {
        this.ordenDeCompra = ordenDeCompra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CLIENTE", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CATALOGO", nullable=false)
    public Catalogo getCatalogo() {
        return this.catalogo;
    }
    
    public void setCatalogo(Catalogo catalogo) {
        this.catalogo = catalogo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="devolucion")
    public Set<DetalleDevolucion> getDetalleDevolucions() {
        return this.detalleDevolucions;
    }
    
    public void setDetalleDevolucions(Set<DetalleDevolucion> detalleDevolucions) {
        this.detalleDevolucions = detalleDevolucions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="devolucion")
    public Set<Transaccion> getTransaccions() {
        return this.transaccions;
    }
    
    public void setTransaccions(Set<Transaccion> transaccions) {
        this.transaccions = transaccions;
    }




}


