package model;
// Generated 17-may-2015 20:35:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Devolucion generated by hbm2java
 */
public class Devolucion  implements java.io.Serializable {


     private int idDevolucion;
     private Catalogo catalogo;
     private Cliente cliente;
     private OrdenDeCompra ordenDeCompra;
     private Proveedor proveedor;
     private Requisicion requisicion;
     private Set<DetalleDevolucion> detalleDevolucions = new HashSet<DetalleDevolucion>(0);
     private Set<Transaccion> transaccions = new HashSet<Transaccion>(0);

    public Devolucion() {
    }

	
    public Devolucion(int idDevolucion, Catalogo catalogo, Cliente cliente, Proveedor proveedor) {
        this.idDevolucion = idDevolucion;
        this.catalogo = catalogo;
        this.cliente = cliente;
        this.proveedor = proveedor;
    }
    public Devolucion(int idDevolucion, Catalogo catalogo, Cliente cliente, OrdenDeCompra ordenDeCompra, Proveedor proveedor, Requisicion requisicion, Set<DetalleDevolucion> detalleDevolucions, Set<Transaccion> transaccions) {
       this.idDevolucion = idDevolucion;
       this.catalogo = catalogo;
       this.cliente = cliente;
       this.ordenDeCompra = ordenDeCompra;
       this.proveedor = proveedor;
       this.requisicion = requisicion;
       this.detalleDevolucions = detalleDevolucions;
       this.transaccions = transaccions;
    }
   
    public int getIdDevolucion() {
        return this.idDevolucion;
    }
    
    public void setIdDevolucion(int idDevolucion) {
        this.idDevolucion = idDevolucion;
    }
    public Catalogo getCatalogo() {
        return this.catalogo;
    }
    
    public void setCatalogo(Catalogo catalogo) {
        this.catalogo = catalogo;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public OrdenDeCompra getOrdenDeCompra() {
        return this.ordenDeCompra;
    }
    
    public void setOrdenDeCompra(OrdenDeCompra ordenDeCompra) {
        this.ordenDeCompra = ordenDeCompra;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Requisicion getRequisicion() {
        return this.requisicion;
    }
    
    public void setRequisicion(Requisicion requisicion) {
        this.requisicion = requisicion;
    }
    public Set<DetalleDevolucion> getDetalleDevolucions() {
        return this.detalleDevolucions;
    }
    
    public void setDetalleDevolucions(Set<DetalleDevolucion> detalleDevolucions) {
        this.detalleDevolucions = detalleDevolucions;
    }
    public Set<Transaccion> getTransaccions() {
        return this.transaccions;
    }
    
    public void setTransaccions(Set<Transaccion> transaccions) {
        this.transaccions = transaccions;
    }




}


