package model;
// Generated 23-may-2015 18:32:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Inventario generated by hbm2java
 */
@Entity
@Table(name="INVENTARIO"
    ,schema="GRUPO8"
)
public class Inventario  implements java.io.Serializable {


     private int idInventario;
     private Empleado empleado;
     private Bodega bodega;
     private String nombre3;
     private BigDecimal monto;
     private Set<Transaccion> transaccions = new HashSet<Transaccion>(0);
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Inventario() {
    }

	
    public Inventario(int idInventario, Empleado empleado, Bodega bodega, String nombre3, BigDecimal monto) {
        this.idInventario = idInventario;
        this.empleado = empleado;
        this.bodega = bodega;
        this.nombre3 = nombre3;
        this.monto = monto;
    }
    public Inventario(int idInventario, Empleado empleado, Bodega bodega, String nombre3, BigDecimal monto, Set<Transaccion> transaccions, Set<Empleado> empleados) {
       this.idInventario = idInventario;
       this.empleado = empleado;
       this.bodega = bodega;
       this.nombre3 = nombre3;
       this.monto = monto;
       this.transaccions = transaccions;
       this.empleados = empleados;
    }
   
     @Id 

    
    @Column(name="ID_INVENTARIO", unique=true, nullable=false, precision=6, scale=0)
    public int getIdInventario() {
        return this.idInventario;
    }
    
    public void setIdInventario(int idInventario) {
        this.idInventario = idInventario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_EMPLEADO", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_BODEGA", nullable=false)
    public Bodega getBodega() {
        return this.bodega;
    }
    
    public void setBodega(Bodega bodega) {
        this.bodega = bodega;
    }

    
    @Column(name="NOMBRE3", nullable=false, length=35)
    public String getNombre3() {
        return this.nombre3;
    }
    
    public void setNombre3(String nombre3) {
        this.nombre3 = nombre3;
    }

    
    @Column(name="MONTO", nullable=false, precision=8)
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="inventario")
    public Set<Transaccion> getTransaccions() {
        return this.transaccions;
    }
    
    public void setTransaccions(Set<Transaccion> transaccions) {
        this.transaccions = transaccions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="inventario")
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


