package model;
// Generated 17-may-2015 20:35:06 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrdenDeCompra generated by hbm2java
 */
public class OrdenDeCompra  implements java.io.Serializable {


     private int idOrden;
     private Cotizacion cotizacion;
     private Empleado empleado;
     private Date fehcaOrden;
     private BigDecimal estadoOrden;
     private BigDecimal fueDevuelto;
     private Set<Devolucion> devolucions = new HashSet<Devolucion>(0);
     private Set<Transaccion> transaccions = new HashSet<Transaccion>(0);
     private Set<DetalleDeOrdenCompra> detalleDeOrdenCompras = new HashSet<DetalleDeOrdenCompra>(0);

    public OrdenDeCompra() {
    }

	
    public OrdenDeCompra(int idOrden, Cotizacion cotizacion, Empleado empleado, Date fehcaOrden, BigDecimal estadoOrden) {
        this.idOrden = idOrden;
        this.cotizacion = cotizacion;
        this.empleado = empleado;
        this.fehcaOrden = fehcaOrden;
        this.estadoOrden = estadoOrden;
    }
    public OrdenDeCompra(int idOrden, Cotizacion cotizacion, Empleado empleado, Date fehcaOrden, BigDecimal estadoOrden, BigDecimal fueDevuelto, Set<Devolucion> devolucions, Set<Transaccion> transaccions, Set<DetalleDeOrdenCompra> detalleDeOrdenCompras) {
       this.idOrden = idOrden;
       this.cotizacion = cotizacion;
       this.empleado = empleado;
       this.fehcaOrden = fehcaOrden;
       this.estadoOrden = estadoOrden;
       this.fueDevuelto = fueDevuelto;
       this.devolucions = devolucions;
       this.transaccions = transaccions;
       this.detalleDeOrdenCompras = detalleDeOrdenCompras;
    }
   
    public int getIdOrden() {
        return this.idOrden;
    }
    
    public void setIdOrden(int idOrden) {
        this.idOrden = idOrden;
    }
    public Cotizacion getCotizacion() {
        return this.cotizacion;
    }
    
    public void setCotizacion(Cotizacion cotizacion) {
        this.cotizacion = cotizacion;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Date getFehcaOrden() {
        return this.fehcaOrden;
    }
    
    public void setFehcaOrden(Date fehcaOrden) {
        this.fehcaOrden = fehcaOrden;
    }
    public BigDecimal getEstadoOrden() {
        return this.estadoOrden;
    }
    
    public void setEstadoOrden(BigDecimal estadoOrden) {
        this.estadoOrden = estadoOrden;
    }
    public BigDecimal getFueDevuelto() {
        return this.fueDevuelto;
    }
    
    public void setFueDevuelto(BigDecimal fueDevuelto) {
        this.fueDevuelto = fueDevuelto;
    }
    public Set<Devolucion> getDevolucions() {
        return this.devolucions;
    }
    
    public void setDevolucions(Set<Devolucion> devolucions) {
        this.devolucions = devolucions;
    }
    public Set<Transaccion> getTransaccions() {
        return this.transaccions;
    }
    
    public void setTransaccions(Set<Transaccion> transaccions) {
        this.transaccions = transaccions;
    }
    public Set<DetalleDeOrdenCompra> getDetalleDeOrdenCompras() {
        return this.detalleDeOrdenCompras;
    }
    
    public void setDetalleDeOrdenCompras(Set<DetalleDeOrdenCompra> detalleDeOrdenCompras) {
        this.detalleDeOrdenCompras = detalleDeOrdenCompras;
    }




}


