package model;
// Generated 23-may-2015 18:32:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrdenDeCompra generated by hbm2java
 */
@Entity
@Table(name="ORDEN_DE_COMPRA"
    ,schema="GRUPO8"
)
public class OrdenDeCompra  implements java.io.Serializable {


     private int idOrden;
     private Empleado empleado;
     private Cotizacion cotizacion;
     private Date fehcaOrden;
     private BigDecimal estadoOrden;
     private BigDecimal fueDevuelto;
     private Set<Devolucion> devolucions = new HashSet<Devolucion>(0);
     private Set<Transaccion> transaccions = new HashSet<Transaccion>(0);
     private Set<DetalleDeOrdenCompra> detalleDeOrdenCompras = new HashSet<DetalleDeOrdenCompra>(0);

    public OrdenDeCompra() {
    }

	
    public OrdenDeCompra(int idOrden, Empleado empleado, Cotizacion cotizacion, Date fehcaOrden, BigDecimal estadoOrden) {
        this.idOrden = idOrden;
        this.empleado = empleado;
        this.cotizacion = cotizacion;
        this.fehcaOrden = fehcaOrden;
        this.estadoOrden = estadoOrden;
    }
    public OrdenDeCompra(int idOrden, Empleado empleado, Cotizacion cotizacion, Date fehcaOrden, BigDecimal estadoOrden, BigDecimal fueDevuelto, Set<Devolucion> devolucions, Set<Transaccion> transaccions, Set<DetalleDeOrdenCompra> detalleDeOrdenCompras) {
       this.idOrden = idOrden;
       this.empleado = empleado;
       this.cotizacion = cotizacion;
       this.fehcaOrden = fehcaOrden;
       this.estadoOrden = estadoOrden;
       this.fueDevuelto = fueDevuelto;
       this.devolucions = devolucions;
       this.transaccions = transaccions;
       this.detalleDeOrdenCompras = detalleDeOrdenCompras;
    }
   
     @Id 

    
    @Column(name="ID_ORDEN", unique=true, nullable=false, precision=6, scale=0)
    public int getIdOrden() {
        return this.idOrden;
    }
    
    public void setIdOrden(int idOrden) {
        this.idOrden = idOrden;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_EMPLEADO", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_COTIZACION", nullable=false)
    public Cotizacion getCotizacion() {
        return this.cotizacion;
    }
    
    public void setCotizacion(Cotizacion cotizacion) {
        this.cotizacion = cotizacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FEHCA_ORDEN", nullable=false, length=7)
    public Date getFehcaOrden() {
        return this.fehcaOrden;
    }
    
    public void setFehcaOrden(Date fehcaOrden) {
        this.fehcaOrden = fehcaOrden;
    }

    
    @Column(name="ESTADO_ORDEN", nullable=false, precision=22, scale=0)
    public BigDecimal getEstadoOrden() {
        return this.estadoOrden;
    }
    
    public void setEstadoOrden(BigDecimal estadoOrden) {
        this.estadoOrden = estadoOrden;
    }

    
    @Column(name="FUE_DEVUELTO", precision=22, scale=0)
    public BigDecimal getFueDevuelto() {
        return this.fueDevuelto;
    }
    
    public void setFueDevuelto(BigDecimal fueDevuelto) {
        this.fueDevuelto = fueDevuelto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ordenDeCompra")
    public Set<Devolucion> getDevolucions() {
        return this.devolucions;
    }
    
    public void setDevolucions(Set<Devolucion> devolucions) {
        this.devolucions = devolucions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ordenDeCompra")
    public Set<Transaccion> getTransaccions() {
        return this.transaccions;
    }
    
    public void setTransaccions(Set<Transaccion> transaccions) {
        this.transaccions = transaccions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ordenDeCompra")
    public Set<DetalleDeOrdenCompra> getDetalleDeOrdenCompras() {
        return this.detalleDeOrdenCompras;
    }
    
    public void setDetalleDeOrdenCompras(Set<DetalleDeOrdenCompra> detalleDeOrdenCompras) {
        this.detalleDeOrdenCompras = detalleDeOrdenCompras;
    }




}


