package model;
// Generated 17-may-2015 20:35:06 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private int idPedido;
     private Empleado empleado;
     private Date fechaPedido;
     private Set<DetallePedido> detallePedidos = new HashSet<DetallePedido>(0);
     private Set<Cotizacion> cotizacions = new HashSet<Cotizacion>(0);

    public Pedido() {
    }

	
    public Pedido(int idPedido, Empleado empleado, Date fechaPedido) {
        this.idPedido = idPedido;
        this.empleado = empleado;
        this.fechaPedido = fechaPedido;
    }
    public Pedido(int idPedido, Empleado empleado, Date fechaPedido, Set<DetallePedido> detallePedidos, Set<Cotizacion> cotizacions) {
       this.idPedido = idPedido;
       this.empleado = empleado;
       this.fechaPedido = fechaPedido;
       this.detallePedidos = detallePedidos;
       this.cotizacions = cotizacions;
    }
   
    public int getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(int idPedido) {
        this.idPedido = idPedido;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Date getFechaPedido() {
        return this.fechaPedido;
    }
    
    public void setFechaPedido(Date fechaPedido) {
        this.fechaPedido = fechaPedido;
    }
    public Set<DetallePedido> getDetallePedidos() {
        return this.detallePedidos;
    }
    
    public void setDetallePedidos(Set<DetallePedido> detallePedidos) {
        this.detallePedidos = detallePedidos;
    }
    public Set<Cotizacion> getCotizacions() {
        return this.cotizacions;
    }
    
    public void setCotizacions(Set<Cotizacion> cotizacions) {
        this.cotizacions = cotizacions;
    }




}


