package model;
// Generated 23-may-2015 18:32:09 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name="PERSONA"
    ,schema="GRUPO8"
)
public class Persona  implements java.io.Serializable {


     private int idPersona;
     private Usuario usuario;
     private String nombre;
     private String apellido;
     private char genero;
     private String dui;
     private String nit;
     private Date fechaNac;
     private String direccion;
     private String correo;
     private Set<Telefono> telefonos = new HashSet<Telefono>(0);

    public Persona() {
    }

	
    public Persona(int idPersona, String nombre, String apellido, char genero, String dui, String nit, Date fechaNac, String direccion) {
        this.idPersona = idPersona;
        this.nombre = nombre;
        this.apellido = apellido;
        this.genero = genero;
        this.dui = dui;
        this.nit = nit;
        this.fechaNac = fechaNac;
        this.direccion = direccion;
    }
    public Persona(int idPersona, Usuario usuario, String nombre, String apellido, char genero, String dui, String nit, Date fechaNac, String direccion, String correo, Set<Telefono> telefonos) {
       this.idPersona = idPersona;
       this.usuario = usuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.genero = genero;
       this.dui = dui;
       this.nit = nit;
       this.fechaNac = fechaNac;
       this.direccion = direccion;
       this.correo = correo;
       this.telefonos = telefonos;
    }
   
     @Id 

    
    @Column(name="ID_PERSONA", unique=true, nullable=false, precision=6, scale=0)
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_USUARIO")
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="NOMBRE", nullable=false, length=55)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="APELLIDO", nullable=false, length=55)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="GENERO", nullable=false, length=1)
    public char getGenero() {
        return this.genero;
    }
    
    public void setGenero(char genero) {
        this.genero = genero;
    }

    
    @Column(name="DUI", nullable=false, length=10)
    public String getDui() {
        return this.dui;
    }
    
    public void setDui(String dui) {
        this.dui = dui;
    }

    
    @Column(name="NIT", nullable=false, length=17)
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_NAC", nullable=false, length=7)
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }

    
    @Column(name="DIRECCION", nullable=false, length=150)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="CORREO", length=80)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
    public Set<Telefono> getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(Set<Telefono> telefonos) {
        this.telefonos = telefonos;
    }




}


