package model;
// Generated 17-may-2015 20:35:06 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private int idProducto;
     private Catalogo catalogo;
     private DetalleProducto detalleProducto;
     private Proveedor proveedor;
     private String nombre4;
     private BigDecimal costo;
     private String codigoProducto;
     private String descripcion;
     private Set<DetalleDevolucion> detalleDevolucions = new HashSet<DetalleDevolucion>(0);
     private Set<DetallePedido> detallePedidos = new HashSet<DetallePedido>(0);
     private Set<DetalleDeOrdenCompra> detalleDeOrdenCompras = new HashSet<DetalleDeOrdenCompra>(0);
     private Set<DetalleRequisicion> detalleRequisicions = new HashSet<DetalleRequisicion>(0);

    public Producto() {
    }

	
    public Producto(int idProducto, Catalogo catalogo, DetalleProducto detalleProducto, Proveedor proveedor, String nombre4, BigDecimal costo, String codigoProducto) {
        this.idProducto = idProducto;
        this.catalogo = catalogo;
        this.detalleProducto = detalleProducto;
        this.proveedor = proveedor;
        this.nombre4 = nombre4;
        this.costo = costo;
        this.codigoProducto = codigoProducto;
    }
    public Producto(int idProducto, Catalogo catalogo, DetalleProducto detalleProducto, Proveedor proveedor, String nombre4, BigDecimal costo, String codigoProducto, String descripcion, Set<DetalleDevolucion> detalleDevolucions, Set<DetallePedido> detallePedidos, Set<DetalleDeOrdenCompra> detalleDeOrdenCompras, Set<DetalleRequisicion> detalleRequisicions) {
       this.idProducto = idProducto;
       this.catalogo = catalogo;
       this.detalleProducto = detalleProducto;
       this.proveedor = proveedor;
       this.nombre4 = nombre4;
       this.costo = costo;
       this.codigoProducto = codigoProducto;
       this.descripcion = descripcion;
       this.detalleDevolucions = detalleDevolucions;
       this.detallePedidos = detallePedidos;
       this.detalleDeOrdenCompras = detalleDeOrdenCompras;
       this.detalleRequisicions = detalleRequisicions;
    }
   
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }
    public Catalogo getCatalogo() {
        return this.catalogo;
    }
    
    public void setCatalogo(Catalogo catalogo) {
        this.catalogo = catalogo;
    }
    public DetalleProducto getDetalleProducto() {
        return this.detalleProducto;
    }
    
    public void setDetalleProducto(DetalleProducto detalleProducto) {
        this.detalleProducto = detalleProducto;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public String getNombre4() {
        return this.nombre4;
    }
    
    public void setNombre4(String nombre4) {
        this.nombre4 = nombre4;
    }
    public BigDecimal getCosto() {
        return this.costo;
    }
    
    public void setCosto(BigDecimal costo) {
        this.costo = costo;
    }
    public String getCodigoProducto() {
        return this.codigoProducto;
    }
    
    public void setCodigoProducto(String codigoProducto) {
        this.codigoProducto = codigoProducto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<DetalleDevolucion> getDetalleDevolucions() {
        return this.detalleDevolucions;
    }
    
    public void setDetalleDevolucions(Set<DetalleDevolucion> detalleDevolucions) {
        this.detalleDevolucions = detalleDevolucions;
    }
    public Set<DetallePedido> getDetallePedidos() {
        return this.detallePedidos;
    }
    
    public void setDetallePedidos(Set<DetallePedido> detallePedidos) {
        this.detallePedidos = detallePedidos;
    }
    public Set<DetalleDeOrdenCompra> getDetalleDeOrdenCompras() {
        return this.detalleDeOrdenCompras;
    }
    
    public void setDetalleDeOrdenCompras(Set<DetalleDeOrdenCompra> detalleDeOrdenCompras) {
        this.detalleDeOrdenCompras = detalleDeOrdenCompras;
    }
    public Set<DetalleRequisicion> getDetalleRequisicions() {
        return this.detalleRequisicions;
    }
    
    public void setDetalleRequisicions(Set<DetalleRequisicion> detalleRequisicions) {
        this.detalleRequisicions = detalleRequisicions;
    }




}


