package model;
// Generated 23-may-2015 18:32:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name="PRODUCTO"
    ,schema="GRUPO8"
)
public class Producto  implements java.io.Serializable {


     private int idProducto;
     private Proveedor proveedor;
     private DetalleProducto detalleProducto;
     private Catalogo catalogo;
     private String nombre4;
     private BigDecimal costo;
     private String codigoProducto;
     private String descripcion;
     private Set<DetalleDevolucion> detalleDevolucions = new HashSet<DetalleDevolucion>(0);
     private Set<DetallePedido> detallePedidos = new HashSet<DetallePedido>(0);
     private Set<DetalleDeOrdenCompra> detalleDeOrdenCompras = new HashSet<DetalleDeOrdenCompra>(0);
     private Set<DetalleRequisicion> detalleRequisicions = new HashSet<DetalleRequisicion>(0);

    public Producto() {
    }

	
    public Producto(int idProducto, Proveedor proveedor, DetalleProducto detalleProducto, Catalogo catalogo, String nombre4, BigDecimal costo, String codigoProducto) {
        this.idProducto = idProducto;
        this.proveedor = proveedor;
        this.detalleProducto = detalleProducto;
        this.catalogo = catalogo;
        this.nombre4 = nombre4;
        this.costo = costo;
        this.codigoProducto = codigoProducto;
    }
    public Producto(int idProducto, Proveedor proveedor, DetalleProducto detalleProducto, Catalogo catalogo, String nombre4, BigDecimal costo, String codigoProducto, String descripcion, Set<DetalleDevolucion> detalleDevolucions, Set<DetallePedido> detallePedidos, Set<DetalleDeOrdenCompra> detalleDeOrdenCompras, Set<DetalleRequisicion> detalleRequisicions) {
       this.idProducto = idProducto;
       this.proveedor = proveedor;
       this.detalleProducto = detalleProducto;
       this.catalogo = catalogo;
       this.nombre4 = nombre4;
       this.costo = costo;
       this.codigoProducto = codigoProducto;
       this.descripcion = descripcion;
       this.detalleDevolucions = detalleDevolucions;
       this.detallePedidos = detallePedidos;
       this.detalleDeOrdenCompras = detalleDeOrdenCompras;
       this.detalleRequisicions = detalleRequisicions;
    }
   
     @Id 

    
    @Column(name="ID_PRODUCTO", unique=true, nullable=false, precision=6, scale=0)
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PROVEEDOR", nullable=false)
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_DETALLE_PRODUCTO", nullable=false)
    public DetalleProducto getDetalleProducto() {
        return this.detalleProducto;
    }
    
    public void setDetalleProducto(DetalleProducto detalleProducto) {
        this.detalleProducto = detalleProducto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CATALOGO", nullable=false)
    public Catalogo getCatalogo() {
        return this.catalogo;
    }
    
    public void setCatalogo(Catalogo catalogo) {
        this.catalogo = catalogo;
    }

    
    @Column(name="NOMBRE4", nullable=false, length=50)
    public String getNombre4() {
        return this.nombre4;
    }
    
    public void setNombre4(String nombre4) {
        this.nombre4 = nombre4;
    }

    
    @Column(name="COSTO", nullable=false, precision=8)
    public BigDecimal getCosto() {
        return this.costo;
    }
    
    public void setCosto(BigDecimal costo) {
        this.costo = costo;
    }

    
    @Column(name="CODIGO_PRODUCTO", nullable=false, length=7)
    public String getCodigoProducto() {
        return this.codigoProducto;
    }
    
    public void setCodigoProducto(String codigoProducto) {
        this.codigoProducto = codigoProducto;
    }

    
    @Column(name="DESCRIPCION", length=150)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="producto")
    public Set<DetalleDevolucion> getDetalleDevolucions() {
        return this.detalleDevolucions;
    }
    
    public void setDetalleDevolucions(Set<DetalleDevolucion> detalleDevolucions) {
        this.detalleDevolucions = detalleDevolucions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="producto")
    public Set<DetallePedido> getDetallePedidos() {
        return this.detallePedidos;
    }
    
    public void setDetallePedidos(Set<DetallePedido> detallePedidos) {
        this.detallePedidos = detallePedidos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="producto")
    public Set<DetalleDeOrdenCompra> getDetalleDeOrdenCompras() {
        return this.detalleDeOrdenCompras;
    }
    
    public void setDetalleDeOrdenCompras(Set<DetalleDeOrdenCompra> detalleDeOrdenCompras) {
        this.detalleDeOrdenCompras = detalleDeOrdenCompras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="producto")
    public Set<DetalleRequisicion> getDetalleRequisicions() {
        return this.detalleRequisicions;
    }
    
    public void setDetalleRequisicions(Set<DetalleRequisicion> detalleRequisicions) {
        this.detalleRequisicions = detalleRequisicions;
    }




}


