package model;
// Generated 23-may-2015 18:32:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Proveedor generated by hbm2java
 */
@Entity
@Table(name="PROVEEDOR"
    ,schema="GRUPO8"
)
public class Proveedor  implements java.io.Serializable {


     private int idProveedor;
     private Catalogo catalogo;
     private String nombre;
     private String correo;
     private String nit;
     private String giro;
     private String nrc;
     private Set<Producto> productos = new HashSet<Producto>(0);
     private Set<Cotizacion> cotizacions = new HashSet<Cotizacion>(0);
     private Set<Devolucion> devolucions = new HashSet<Devolucion>(0);

    public Proveedor() {
    }

	
    public Proveedor(int idProveedor, Catalogo catalogo, String nombre, String nit, String nrc) {
        this.idProveedor = idProveedor;
        this.catalogo = catalogo;
        this.nombre = nombre;
        this.nit = nit;
        this.nrc = nrc;
    }
    public Proveedor(int idProveedor, Catalogo catalogo, String nombre, String correo, String nit, String giro, String nrc, Set<Producto> productos, Set<Cotizacion> cotizacions, Set<Devolucion> devolucions) {
       this.idProveedor = idProveedor;
       this.catalogo = catalogo;
       this.nombre = nombre;
       this.correo = correo;
       this.nit = nit;
       this.giro = giro;
       this.nrc = nrc;
       this.productos = productos;
       this.cotizacions = cotizacions;
       this.devolucions = devolucions;
    }
   
     @Id 

    
    @Column(name="ID_PROVEEDOR", unique=true, nullable=false, precision=6, scale=0)
    public int getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(int idProveedor) {
        this.idProveedor = idProveedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CATALOGO", nullable=false)
    public Catalogo getCatalogo() {
        return this.catalogo;
    }
    
    public void setCatalogo(Catalogo catalogo) {
        this.catalogo = catalogo;
    }

    
    @Column(name="NOMBRE", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="CORREO", length=50)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="NIT", nullable=false, length=17)
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }

    
    @Column(name="GIRO", length=150)
    public String getGiro() {
        return this.giro;
    }
    
    public void setGiro(String giro) {
        this.giro = giro;
    }

    
    @Column(name="NRC", nullable=false, length=50)
    public String getNrc() {
        return this.nrc;
    }
    
    public void setNrc(String nrc) {
        this.nrc = nrc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proveedor")
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proveedor")
    public Set<Cotizacion> getCotizacions() {
        return this.cotizacions;
    }
    
    public void setCotizacions(Set<Cotizacion> cotizacions) {
        this.cotizacions = cotizacions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proveedor")
    public Set<Devolucion> getDevolucions() {
        return this.devolucions;
    }
    
    public void setDevolucions(Set<Devolucion> devolucions) {
        this.devolucions = devolucions;
    }




}


