package model;
// Generated 23-may-2015 18:32:09 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Telefono generated by hbm2java
 */
@Entity
@Table(name="TELEFONO"
    ,schema="GRUPO8"
)
public class Telefono  implements java.io.Serializable {


     private int idTelefono;
     private Persona persona;
     private String numTelefono;

    public Telefono() {
    }

    public Telefono(int idTelefono, Persona persona, String numTelefono) {
       this.idTelefono = idTelefono;
       this.persona = persona;
       this.numTelefono = numTelefono;
    }
   
     @Id 

    
    @Column(name="ID_TELEFONO", unique=true, nullable=false, precision=6, scale=0)
    public int getIdTelefono() {
        return this.idTelefono;
    }
    
    public void setIdTelefono(int idTelefono) {
        this.idTelefono = idTelefono;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PERSONA", nullable=false)
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    
    @Column(name="NUM_TELEFONO", nullable=false, length=256)
    public String getNumTelefono() {
        return this.numTelefono;
    }
    
    public void setNumTelefono(String numTelefono) {
        this.numTelefono = numTelefono;
    }




}


