package model;
// Generated 17-may-2015 20:35:06 by Hibernate Tools 4.3.1



/**
 * Telefono generated by hbm2java
 */
public class Telefono  implements java.io.Serializable {


     private int idTelefono;
     private Persona persona;
     private String numTelefono;

    public Telefono() {
    }

    public Telefono(int idTelefono, Persona persona, String numTelefono) {
       this.idTelefono = idTelefono;
       this.persona = persona;
       this.numTelefono = numTelefono;
    }
   
    public int getIdTelefono() {
        return this.idTelefono;
    }
    
    public void setIdTelefono(int idTelefono) {
        this.idTelefono = idTelefono;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getNumTelefono() {
        return this.numTelefono;
    }
    
    public void setNumTelefono(String numTelefono) {
        this.numTelefono = numTelefono;
    }




}


