package model;
// Generated 17-may-2015 20:35:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoCatalogo generated by hbm2java
 */
public class TipoCatalogo  implements java.io.Serializable {


     private int idTipoCatalogo;
     private String nombre;
     private Set<Catalogo> catalogos = new HashSet<Catalogo>(0);

    public TipoCatalogo() {
    }

	
    public TipoCatalogo(int idTipoCatalogo, String nombre) {
        this.idTipoCatalogo = idTipoCatalogo;
        this.nombre = nombre;
    }
    public TipoCatalogo(int idTipoCatalogo, String nombre, Set<Catalogo> catalogos) {
       this.idTipoCatalogo = idTipoCatalogo;
       this.nombre = nombre;
       this.catalogos = catalogos;
    }
   
    public int getIdTipoCatalogo() {
        return this.idTipoCatalogo;
    }
    
    public void setIdTipoCatalogo(int idTipoCatalogo) {
        this.idTipoCatalogo = idTipoCatalogo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Catalogo> getCatalogos() {
        return this.catalogos;
    }
    
    public void setCatalogos(Set<Catalogo> catalogos) {
        this.catalogos = catalogos;
    }




}


