package model;
// Generated 17-may-2015 20:35:06 by Hibernate Tools 4.3.1



/**
 * Transaccion generated by hbm2java
 */
public class Transaccion  implements java.io.Serializable {


     private int idTransaccion;
     private Catalogo catalogo;
     private Devolucion devolucion;
     private Inventario inventario;
     private OrdenDeCompra ordenDeCompra;
     private Requisicion requisicion;

    public Transaccion() {
    }

	
    public Transaccion(int idTransaccion, Catalogo catalogo, Inventario inventario) {
        this.idTransaccion = idTransaccion;
        this.catalogo = catalogo;
        this.inventario = inventario;
    }
    public Transaccion(int idTransaccion, Catalogo catalogo, Devolucion devolucion, Inventario inventario, OrdenDeCompra ordenDeCompra, Requisicion requisicion) {
       this.idTransaccion = idTransaccion;
       this.catalogo = catalogo;
       this.devolucion = devolucion;
       this.inventario = inventario;
       this.ordenDeCompra = ordenDeCompra;
       this.requisicion = requisicion;
    }
   
    public int getIdTransaccion() {
        return this.idTransaccion;
    }
    
    public void setIdTransaccion(int idTransaccion) {
        this.idTransaccion = idTransaccion;
    }
    public Catalogo getCatalogo() {
        return this.catalogo;
    }
    
    public void setCatalogo(Catalogo catalogo) {
        this.catalogo = catalogo;
    }
    public Devolucion getDevolucion() {
        return this.devolucion;
    }
    
    public void setDevolucion(Devolucion devolucion) {
        this.devolucion = devolucion;
    }
    public Inventario getInventario() {
        return this.inventario;
    }
    
    public void setInventario(Inventario inventario) {
        this.inventario = inventario;
    }
    public OrdenDeCompra getOrdenDeCompra() {
        return this.ordenDeCompra;
    }
    
    public void setOrdenDeCompra(OrdenDeCompra ordenDeCompra) {
        this.ordenDeCompra = ordenDeCompra;
    }
    public Requisicion getRequisicion() {
        return this.requisicion;
    }
    
    public void setRequisicion(Requisicion requisicion) {
        this.requisicion = requisicion;
    }




}


