package model;
// Generated 17-may-2015 20:35:06 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private Catalogo catalogo;
     private String nombreUsuario;
     private String contrasena;
     private Serializable fechaCreacion;
     private Serializable fechaModificacion;
     private Set<Persona> personas = new HashSet<Persona>(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario, String nombreUsuario, String contrasena, Serializable fechaCreacion) {
        this.idUsuario = idUsuario;
        this.nombreUsuario = nombreUsuario;
        this.contrasena = contrasena;
        this.fechaCreacion = fechaCreacion;
    }
    public Usuario(int idUsuario, Catalogo catalogo, String nombreUsuario, String contrasena, Serializable fechaCreacion, Serializable fechaModificacion, Set<Persona> personas) {
       this.idUsuario = idUsuario;
       this.catalogo = catalogo;
       this.nombreUsuario = nombreUsuario;
       this.contrasena = contrasena;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.personas = personas;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Catalogo getCatalogo() {
        return this.catalogo;
    }
    
    public void setCatalogo(Catalogo catalogo) {
        this.catalogo = catalogo;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Serializable getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Serializable fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Serializable getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Serializable fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }




}


