package model;
// Generated 23-may-2015 18:32:09 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="USUARIO"
    ,schema="GRUPO8"
)
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private Catalogo catalogo;
     private String nombreUsuario;
     private String contrasena;
     private Serializable fechaCreacion;
     private Serializable fechaModificacion;
     private Set<Persona> personas = new HashSet<Persona>(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario, String nombreUsuario, String contrasena, Serializable fechaCreacion) {
        this.idUsuario = idUsuario;
        this.nombreUsuario = nombreUsuario;
        this.contrasena = contrasena;
        this.fechaCreacion = fechaCreacion;
    }
    public Usuario(int idUsuario, Catalogo catalogo, String nombreUsuario, String contrasena, Serializable fechaCreacion, Serializable fechaModificacion, Set<Persona> personas) {
       this.idUsuario = idUsuario;
       this.catalogo = catalogo;
       this.nombreUsuario = nombreUsuario;
       this.contrasena = contrasena;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.personas = personas;
    }
   
     @Id 

    
    @Column(name="ID_USUARIO", unique=true, nullable=false, precision=6, scale=0)
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CATALOGO")
    public Catalogo getCatalogo() {
        return this.catalogo;
    }
    
    public void setCatalogo(Catalogo catalogo) {
        this.catalogo = catalogo;
    }

    
    @Column(name="NOMBRE_USUARIO", nullable=false, length=20)
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }

    
    @Column(name="CONTRASENA", nullable=false, length=16)
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    
    @Column(name="FECHA_CREACION", nullable=false)
    public Serializable getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Serializable fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    
    @Column(name="FECHA_MODIFICACION")
    public Serializable getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Serializable fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }




}


